apiVersion: v1
kind: Secret
metadata:  
  name: frontend-secrets
  namespace: phpipam
type: Opaque  
stringData:  
  IPAM_DATABASE_HOST: phpipam-mysql
  IPAM_DATABASE_PASSWORD: password
  IPAM_DATABASE_WEBHOST: '%'
  SCAN_INTERVAL: 5m
