apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  ports:
    - port: 3000
  selector:
    app: grafana
    tier: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.31.202
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: grafana
    spec:
      securityContext:
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: grafana-pv
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
