apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-local
  labels:
    app: grafana
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
