apiVersion: v1
kind: Secret
metadata:  
  name: influxdb-secrets
  namespace: grafana
type: Opaque  
stringData:  
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: influx
  INFLUXDB_ADMIN_PASSWORD: secret_password
  INFLUXDB_DB: vmware
  INFLUXDB_USER: telegraf
  INFLUXDB_USER_PASSWORD: secret_password
