apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: grafana
  namespace: grafana
spec:
  ports:
    - port: 8086
  selector:
    app: grafana
    tier: influxdb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-pv
          mountPath: /var/lib/influxdb
        - name: influxdb-config
          mountPath: influxdb-config
          subPath: influxdb.conf
          readOnly: true
        envFrom:
        - secretRef:
            name: influxdb-secrets
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pvc
      - name: influxdb-config
        configMap:
          name: influxdb-config
