apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pvc
  namespace: elastic
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: elastic
spec:
  capacity:
    storage: 1Gi
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volumes/NFS01_K8SHDD_01/elastic
    server: 192.168.36.41
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: elastic
    name: elastic-pvc
