kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vsphereclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

